const {
  dbInstallation,
} = require("../../database/models/installationModel.js");

const User = require("../../database/models/userModel");

const appHomeOpened = async ({ event, client, logger }) => {
  try {
    if (!event.view) return;

    const teamId = event.view.app_installed_team_id;

    // get installation
    const installation = await dbInstallation.findOne({ _id: teamId });

    let blocks = [];

    if (installation.servicenow && installation.servicenow.instance_url) {
      blocks = await connectedInstanceBody(event.user, installation);
    } else {
      blocks = await unconnectedInstanceBody(event.user);
    }

    await client.views.publish({
      // Use the user ID associated with the event
      user_id: event.user,
      view: {
        // Home tabs must be enabled in your app configuration page under "App Home"
        type: "home",
        blocks,
      },
    });
  } catch (err) {
    console.error(err);
  }
};

const unconnectedInstanceBody = (userId) => {
  return [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `Welcome <@${userId}> ! A few things must be configured to get started.`,
      },
    },
    {
      type: "divider",
    },
    {
      type: "header",
      text: {
        type: "plain_text",
        text: "Prepare your ServiceNow instance",
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "In order to use this app, OAuth must be activated on your ServiceNow instance. If it is not, please activate it following this ServiceNow documentation before proceeding.",
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "*1.* Create an *OAuth API endpoint* for external clients following this <https://docs.servicenow.com/bundle/paris-platform-administration/page/administer/security/task/t_CreateEndpointforExternalClients.html|ServiceNow documentation.>",
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "*2.* Take note of the *Client ID* and *Client Secret* generated by ServiceNow for the step below.",
      },
    },

    {
      type: "divider",
    },
    {
      type: "header",
      text: {
        type: "plain_text",
        text: "Connect your ServiceNow instance to Slack",
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "Use the OAuth Client ID and Client Secret you generated in ServiceNow to connect ServiceNow to Slack.",
      },
    },
    {
      type: "actions",
      elements: [
        {
          type: "button",
          text: {
            type: "plain_text",
            text: "Connect ServiceNow to Slack",
            emoji: true,
          },
          value: "connect_servicenow_btn",
          action_id: "open_connect_servicenow",
        },
      ],
    },
  ];
};

const connectedInstanceBody = async (userId, installation) => {
  const blocks = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: "ServiceNow for Slack",
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `Hi <@${userId}> Your Slack workspace is connected to your ServiceNow instance at ${installation.servicenow.instance_url}`,
      },
      accessory: {
        type: "button",
        text: {
          type: "plain_text",
          text: "Disconnect instance",
        },
        style: "danger",
        value: "disconnect_instance_btn",
        action_id: "disconnect_instance",
      },
    },
  ];

  // check if user has account
  const user = await User.findOne({ _id: userId });

  if (user) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: "You have connected your ServiceNow account with this Slack workspace.",
      },
      accessory: {
        type: "button",
        text: {
          type: "plain_text",
          text: "Disconnect account",
          emoji: true,
        },
        style: "danger",
        value: "disconnect_account-btn",
        action_id: "disconnect_account",
      },
    });
  } else {
    blocks.push(
      {
        type: "header",
        text: {
          type: "plain_text",
          text: "Connect your account",
          emoji: true,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: "Connect your ServiceNow account to Slack to begin using features like creating ServiceNow incidents, searching ServiceNow, and viewing your recent tickets from within Slack.",
        },
      },
      {
        type: "actions",
        elements: [
          {
            type: "button",
            text: {
              type: "plain_text",
              text: "Connect your account",
              emoji: true,
            },
            style: "primary",
            value: "connect_account_btn",
            url: `${installation.servicenow.instance_url}/oauth_auth.do?response_type=code&redirect_uri=${process.env.REDIRECT_URL}&client_id=${installation.servicenow.client_id}&state=${userId}-${installation.team.id}`,
            action_id: "connect_account",
          },
        ],
      }
    );
  }

  return blocks;
};

module.exports = {
  appHomeOpened,
  unconnectedInstanceBody,
  connectedInstanceBody,
};
